#!/bin/bash

# Script to generate a single LLM-friendly documentation file for Medusa v1
# This concatenates all MDX files from the Medusa v1 docs following the sidebar structure
# Run this script from the root of a Medusa v1 repository

# Configuration
DOCS_PATH="www/apps/docs/content"
SIDEBARS_PATH="www/apps/docs/sidebars.js"
OUTPUT_FILE="medusa-v1-llm-full.txt"

echo "==========================================="
echo "Medusa v1 Documentation Aggregator"
echo "Following Sidebar Structure"
echo "==========================================="
echo ""

# Check if we're in the right place
if [ ! -f "$SIDEBARS_PATH" ]; then
    echo "Error: sidebars.js not found at $SIDEBARS_PATH"
    echo "Please run this script from the root of the Medusa v1 repository"
    exit 1
fi

if [ ! -d "$DOCS_PATH" ]; then
    echo "Error: docs content directory not found at $DOCS_PATH"
    echo "Please run this script from the root of the Medusa v1 repository"
    exit 1
fi

# Create a temporary node script to parse sidebars.js
cat > parse_sidebars.js << 'NODEJS_SCRIPT'
import fs from 'fs';
import path from 'path';

// Read and evaluate sidebars.js
const sidebarsContent = fs.readFileSync('www/apps/docs/sidebars.js', 'utf8');
const module = { exports: {} };
eval(sidebarsContent);
const sidebars = module.exports;

// Function to extract all doc IDs in order
function extractDocIds(items, result = []) {
    if (!items) return result;
    
    for (const item of items) {
        if (typeof item === 'string') {
            // Skip HTML values and dividers
            continue;
        }
        
        if (item.type === 'doc') {
            result.push(item.id);
        } else if (item.type === 'ref' && item.id) {
            // Include refs as they point to actual docs
            result.push(item.id);
        } else if (item.type === 'category' && item.link && item.link.type === 'doc') {
            // Category with a doc link
            result.push(item.link.id);
        }
        
        // Recursively process items
        if (item.items) {
            extractDocIds(item.items, result);
        }
        
        // For autogenerated, we'll need to handle differently
        if (item.type === 'autogenerated' && item.dirName) {
            result.push(`AUTOGEN:${item.dirName}`);
        }
    }
    
    return result;
}

// Process each sidebar section in order
const sidebarOrder = [
    'homepage',
    'modules', 
    'core',
    'upgradeGuides',
    'troubleshooting',
    'plugins',
    'userGuideSidebar',
    'experimentalSidebar',
    'servicesSidebar',
    'jsClientSidebar',
    'entitiesSidebar',
    'pricingReference',
    'productReference',
    'inventoryReference',
    'stockLocationReference',
    'workflowsSidebar',
    'medusaReactSidebar'
];

const processedIds = new Set();

for (const sidebarName of sidebarOrder) {
    if (sidebars[sidebarName]) {
        console.log(`# SECTION: ${sidebarName}`);
        const docIds = extractDocIds(sidebars[sidebarName]);
        
        // Output unique doc IDs that haven't been processed yet
        docIds.forEach(id => {
            if (!processedIds.has(id)) {
                console.log(id);
                processedIds.add(id);
            }
        });
    }
}
NODEJS_SCRIPT

# Run the node script to get ordered doc IDs
echo "Parsing sidebar structure..."
node parse_sidebars.js > doc_ids_ordered.txt

# Start the output file with a header
cat > "$OUTPUT_FILE" << 'HEADER'
================================
MEDUSA V1 DOCUMENTATION
================================
Purpose: LLM-friendly single file containing all Medusa v1 documentation
Note: Ordered according to sidebars.js structure
================================

TABLE OF CONTENTS
================================
HEADER

# Function to clean MDX content
clean_mdx() {
    sed -E \
        -e 's/<[^>]*>//g' \
        -e 's/^import .*//' \
        -e 's/^export .*//' \
        -e '/^```[\s]*$/,/^```[\s]*$/!s/```[a-z]*//g' \
        -e 's/{\/\*.*\*\/}//g' \
        -e 's/className="[^"]*"//g' \
        -e 's/style={{[^}]*}}//g' | \
    sed '/^$/N;/\n$/d'
}

# Function to find and process a doc file
process_doc() {
    local doc_id="$1"
    local doc_path=""
    
    # Convert doc ID to potential file paths
    local potential_paths=(
        "$DOCS_PATH/${doc_id}.mdx"
        "$DOCS_PATH/${doc_id}.md"
        "$DOCS_PATH/${doc_id}/index.mdx"
        "$DOCS_PATH/${doc_id}/index.md"
    )
    
    for path in "${potential_paths[@]}"; do
        if [ -f "$path" ]; then
            doc_path="$path"
            break
        fi
    done
    
    if [ -n "$doc_path" ]; then
        echo "  Processing: $doc_path"
        
        # Add to table of contents
        echo "- $doc_id" >> "$OUTPUT_FILE"
        
        # Store path for later processing
        echo "$doc_path" >> docs_to_process.txt
        return 0
    else
        echo "  Warning: Could not find file for doc ID: $doc_id" >&2
        return 1
    fi
}

# Function to process autogenerated directories
process_autogen_dir() {
    local dir_name="$1"
    local full_path="$DOCS_PATH/$dir_name"
    
    if [ -d "$full_path" ]; then
        echo "  Processing autogenerated directory: $dir_name"
        find "$full_path" -name "*.mdx" -o -name "*.md" | sort | while read -r file; do
            local relative_path="${file#$DOCS_PATH/}"
            echo "- [AUTO] $relative_path" >> "$OUTPUT_FILE"
            echo "$file" >> docs_to_process.txt
        done
    else
        echo "  Warning: Autogenerated directory not found: $dir_name" >&2
    fi
}

# Clear the docs to process file
> docs_to_process.txt

# Process all doc IDs from the sidebar
echo "Building table of contents..."
current_section=""
while IFS= read -r line; do
    if [[ "$line" == "# SECTION:"* ]]; then
        current_section="${line#\# SECTION: }"
        echo "" >> "$OUTPUT_FILE"
        echo "## $current_section" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "Processing section: $current_section"
    elif [[ "$line" == "AUTOGEN:"* ]]; then
        dir_name="${line#AUTOGEN:}"
        process_autogen_dir "$dir_name"
    elif [ -n "$line" ]; then
        process_doc "$line"
    fi
done < doc_ids_ordered.txt

# Add content separator
echo "" >> "$OUTPUT_FILE"
echo "================================" >> "$OUTPUT_FILE"
echo "DOCUMENTATION CONTENT" >> "$OUTPUT_FILE"
echo "================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Process each file and add content
echo ""
echo "Processing documentation content..."
file_count=0
total_files=$(wc -l < docs_to_process.txt)

while IFS= read -r file_path; do
    file_count=$((file_count + 1))
    relative_path="${file_path#$DOCS_PATH/}"
    
    echo "  [$file_count/$total_files] Processing: $relative_path"
    
    # Add file separator and path
    cat >> "$OUTPUT_FILE" << FILE_HEADER

================================
FILE: $relative_path
================================

FILE_HEADER
    
    # Process the file content
    cat "$file_path" | clean_mdx >> "$OUTPUT_FILE"
    
    # Add section separator
    echo "" >> "$OUTPUT_FILE"
    echo "---" >> "$OUTPUT_FILE"
done < docs_to_process.txt

# Add footer with statistics
echo "" >> "$OUTPUT_FILE"
echo "================================" >> "$OUTPUT_FILE"
echo "END OF DOCUMENTATION" >> "$OUTPUT_FILE"
echo "================================" >> "$OUTPUT_FILE"
echo "Total files processed: $file_count" >> "$OUTPUT_FILE"
echo "Generated on: $(date)" >> "$OUTPUT_FILE"

# Clean up temporary files
rm -f parse_sidebars.js doc_ids_ordered.txt docs_to_process.txt

# Final report
echo ""
echo "==========================================="
echo "✅ Documentation generation complete!"
echo "==========================================="
echo "Output file: $OUTPUT_FILE"
echo "File size: $(du -h "$OUTPUT_FILE" | cut -f1)"
echo "Total files processed: $file_count"
echo ""
echo "The documentation has been ordered according to sidebars.js structure."
echo "You can now use this file to provide Medusa v1 context to Claude or other LLMs."